export const PROPERTY_TYPES = ["hotel", "office", "home"];

export const AC_BRANDS = Object.freeze({
  DAIKIN: 'DAIKIN',
  DAIKIN2: 'DAIKIN2',
  DAIKIN64: 'DAIKIN64',
  DAIKIN128: 'DAIKIN128',
  DAIKIN152: 'DAIKIN152',
  DAIKIN160: 'DAIKIN160',
  DAIKIN176: 'DAIKIN176',
  DAIKIN200: 'DAIKIN200',
  DAIKIN216: 'DAIKIN216',
  DAIKIN312: 'DAIKIN312',
  MITSUBISHI_AC: 'MITSUBISHI_AC',
  MITSUBISHI_HEAVY_88: 'MITSUBISHI_HEAVY_88',
  MITSUBISHI_HEAVY_152: 'MITSUBISHI_HEAVY_152',
  MITSUBISHI112: 'MITSUBISHI112',
  MITSUBISHI136: 'MITSUBISHI136',
  MITSUBISHI: 'MITSUBISHI',
  PANASONIC_AC: 'PANASONIC_AC',
  PANASONIC_AC32: 'PANASONIC_AC32',
  PANASONIC: 'PANASONIC',
  LG: 'LG',
  LG2: 'LG2',
  SAMSUNG_AC: 'SAMSUNG_AC',
  SAMSUNG: 'SAMSUNG',
  VOLTAS: 'VOLTAS',
  KELON: 'KELON',
  KELON168: 'KELON168',
  HITACHI_AC: 'HITACHI_AC',
  HITACHI_AC1: 'HITACHI_AC1',
  HITACHI_AC2: 'HITACHI_AC2',
  HITACHI_AC3: 'HITACHI_AC3',
  HITACHI_AC264: 'HITACHI_AC264',
  HITACHI_AC296: 'HITACHI_AC296',
  HITACHI_AC344: 'HITACHI_AC344',
  HITACHI_AC424: 'HITACHI_AC424',
  CARRIER_AC: 'CARRIER_AC',
  CARRIER_AC40: 'CARRIER_AC40',
  CARRIER_AC64: 'CARRIER_AC64',
  CARRIER_AC84: 'CARRIER_AC84',
  CARRIER_AC128: 'CARRIER_AC128',
  TOSHIBA_AC: 'TOSHIBA_AC',
  MIDEA: 'MIDEA',
  MIDEA24: 'MIDEA24',
});

export const AC_BRAND_LABELS = Object.freeze({
  DAIKIN: 'Daikin (Standard)',
  DAIKIN2: 'Daikin (Daikin 2)',
  DAIKIN64: 'Daikin (64-Bit)',
  DAIKIN128: 'Daikin (128-Bit)',
  DAIKIN152: 'Daikin (152-Bit)',
  DAIKIN160: 'Daikin (160-Bit)',
  DAIKIN176: 'Daikin (176-Bit)',
  DAIKIN200: 'Daikin (200-Bit)',
  DAIKIN216: 'Daikin (216-Bit)',
  DAIKIN312: 'Daikin (312-Bit)',
  MITSUBISHI_AC: 'Mitsubishi (Standard)',
  MITSUBISHI_HEAVY_88: 'Mitsubishi Heavy (88-Bit)',
  MITSUBISHI_HEAVY_152: 'Mitsubishi Heavy (152-Bit)',
  MITSUBISHI112: 'Mitsubishi (112-Bit)',
  MITSUBISHI136: 'Mitsubishi (136-Bit)',
  MITSUBISHI: 'Mitsubishi (TV/Non-AC)',
  PANASONIC_AC: 'Panasonic (Standard)',
  PANASONIC_AC32: 'Panasonic (32-Bit)',
  PANASONIC: 'Panasonic (TV/Non-AC)',
  LG: 'LG (Standard)',
  LG2: 'LG (LG2 Protocol)',
  SAMSUNG_AC: 'Samsung (Standard)',
  SAMSUNG: 'Samsung (TV/Non-AC)',
  VOLTAS: 'Voltas (Standard)',
  KELON: 'Kelon',
  KELON168: 'Kelon (168-Bit)',
  HITACHI_AC: 'Hitachi (Standard)',
  HITACHI_AC1: 'Hitachi (AC1 Protocol)',
  HITACHI_AC2: 'Hitachi (AC2 Protocol)',
  HITACHI_AC3: 'Hitachi (AC3 Protocol)',
  HITACHI_AC264: 'Hitachi (AC264 Protocol)',
  HITACHI_AC296: 'Hitachi (AC296 Protocol)',
  HITACHI_AC344: 'Hitachi (AC344 Protocol)',
  HITACHI_AC424: 'Hitachi (AC424 Protocol)',
  CARRIER_AC: 'Carrier (Standard)',
  CARRIER_AC40: 'Carrier (AC40 Protocol)',
  CARRIER_AC64: 'Carrier (AC64 Protocol)',
  CARRIER_AC84: 'Carrier (AC84 Protocol)',
  CARRIER_AC128: 'Carrier (AC128 Protocol)',
  TOSHIBA_AC: 'Toshiba (Standard)',
  MIDEA: 'Midea (Standard)',
  MIDEA24: 'Midea (24-Bit)',
});
